export const light = {
  background: "#fff",
  onBackground: "#181818",
  backgroundSearch: "#F0F0F0",
  onBackgroundSearch: "#7C7C7C",
  primary: "#fff",
  onPrimary: "#000",
  text: "#131313",
  placeholder: "#7d7d7d",
  border: "#A0A0A0",
  textSecoundary: "#7C7C7C",
  yellow: "#fdffde",
  yellowAccent: "#eeff00",
};
export const dark = {
  background: "#181818",
  onBackground: "#fff",
  backgroundSearch: "#7C7C7C",
  onBackgroundSearch: "#F0F0F0",
  primary: "#000",
  onPrimary: "#fff",
  text: "#fff",
  placeholder: "#b0b0b0",
  border: "#A0A0A0",
  textSecoundary: "#fff",
  yellow: "#fdffde",
  yellowAccent: "#eeff00",
};
export const cardColors = [
  "#D9E8FC",
  "#FFD8F4",
  "#FDE99D",
  "#B0E9CA",
  "#FCFAD9",
  "#FFEADD",
];
